'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { TrendingUp, Users, Percent, Clock, Award, CheckCircle2, ArrowRight, ExternalLink } from 'lucide-react';
import Navbar from '@/components/sections/Navbar';
import Footer from '@/components/sections/Footer';

const benefits = [
  {
    icon: Percent,
    title: 'Volume-Based Earnings',
    description: 'Earn competitive commissions based on trading volume generated by your referrals. Lifetime recurring earnings on active users.',
  },
  {
    icon: Clock,
    title: 'Real-Time Tracking',
    description: 'Comprehensive dashboard showing clicks, conversions, and earnings. Full transparency into your affiliate performance.',
  },
  {
    icon: Users,
    title: 'Lifetime Attribution',
    description: 'Your referrals remain yours forever. Earn commissions on all their future trading activity with no expiration.',
  },
  {
    icon: TrendingUp,
    title: 'Scalable Compensation',
    description: 'Commission structure scales with performance. Higher volume partners receive enhanced compensation terms.',
  },
  {
    icon: Award,
    title: 'Dedicated Support',
    description: 'Direct access to our affiliate team for campaign optimization, technical assistance, and strategic guidance.',
  },
];

export default function AffiliatesPage() {
  return (
    <main className="min-h-screen w-full bg-background">
      <Navbar />

      <section className="container mx-auto px-6 lg:px-8 pt-32 pb-32">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="max-w-5xl mx-auto"
        >
          {/* Header */}
          <div className="text-center mb-20">
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="inline-flex items-center gap-2 px-3.5 py-1.5 bg-accent/50 text-foreground/80 rounded-full mb-8 border border-border/50"
            >
              <div className="w-1.5 h-1.5 bg-primary rounded-full animate-pulse" />
              <span className="text-sm professional-text">
                Affiliate Program
              </span>
            </motion.div>

            <h1 className="text-3xl md:text-4xl lg:text-5xl text-foreground mb-6 heading-text">
              Earn with Cryptocoop
            </h1>
            <p className="text-xl text-muted-foreground professional-text leading-relaxed max-w-3xl mx-auto">
              Partner with a leading cryptocurrency exchange and earn competitive commissions on every referral.
            </p>
          </div>

          {/* Value Proposition */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mb-20"
          >
            <div className="bg-gradient-to-br from-primary/10 to-primary/5 p-10 md:p-12 border border-primary/20 rounded-lg text-center">
              <h2 className="text-2xl md:text-3xl text-foreground mb-4 heading-text">
                Earn from Trading Volume
              </h2>
              <p className="text-[15px] text-muted-foreground professional-text mb-6 max-w-2xl mx-auto leading-relaxed">
                Our affiliate program rewards partners based on the trading volume they generate. Commission terms are tailored to each partnership, considering audience size, traffic quality, and expected volume.
              </p>
              <div className="grid md:grid-cols-3 gap-6 mt-8">
                <div className="bg-card p-6 rounded-lg border border-border">
                  <p className="text-sm text-muted-foreground professional-text mb-2">Based on</p>
                  <p className="text-lg text-foreground heading-text">Trading Volume</p>
                </div>
                <div className="bg-card p-6 rounded-lg border border-border">
                  <p className="text-sm text-muted-foreground professional-text mb-2">Attribution</p>
                  <p className="text-lg text-foreground heading-text">Lifetime Tracking</p>
                </div>
                <div className="bg-card p-6 rounded-lg border border-border">
                  <p className="text-sm text-muted-foreground professional-text mb-2">Payouts</p>
                  <p className="text-lg text-foreground heading-text">Monthly</p>
                </div>
              </div>
              <p className="mt-6 text-sm text-muted-foreground professional-text">
                Commission rates negotiated individually based on partnership terms
              </p>
            </div>
          </motion.div>

          {/* Benefits */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="mb-20"
          >
            <h2 className="text-2xl md:text-3xl text-foreground mb-8 heading-text">
              Program Benefits
            </h2>
            
            <div className="grid md:grid-cols-2 gap-6">
              {benefits.map((benefit, index) => (
                <motion.div
                  key={benefit.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.5 + index * 0.1 }}
                  className="bg-card p-6 border border-border rounded-lg"
                >
                  <div className="w-10 h-10 bg-accent rounded-lg flex items-center justify-center mb-4">
                    <benefit.icon className="w-5 h-5 text-foreground" strokeWidth={1.5} />
                  </div>
                  <h3 className="text-lg text-foreground heading-text mb-2">
                    {benefit.title}
                  </h3>
                  <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                    {benefit.description}
                  </p>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* How It Works */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="mb-20"
          >
            <h2 className="text-2xl md:text-3xl text-foreground mb-8 heading-text">
              How It Works
            </h2>
            
            <div className="bg-card p-10 border border-border rounded-lg">
              <div className="space-y-6">
                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-accent rounded-lg flex items-center justify-center text-foreground professional-text font-medium flex-shrink-0 text-sm">
                    1
                  </div>
                  <div>
                    <h3 className="text-base text-foreground heading-text mb-2">Apply to Join</h3>
                    <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                      Submit your application with details about your audience and promotion channels. We review applications within 48 hours.
                    </p>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-accent rounded-lg flex items-center justify-center text-foreground professional-text font-medium flex-shrink-0 text-sm">
                    2
                  </div>
                  <div>
                    <h3 className="text-base text-foreground heading-text mb-2">Get Your Tracking Links</h3>
                    <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                      Receive unique referral links and promotional materials. Access your personalized dashboard for real-time analytics.
                    </p>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-accent rounded-lg flex items-center justify-center text-foreground professional-text font-medium flex-shrink-0 text-sm">
                    3
                  </div>
                  <div>
                    <h3 className="text-base text-foreground heading-text mb-2">Promote & Earn</h3>
                    <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                      Share your links through your channels. Earn commissions automatically on every trade your referrals make.
                    </p>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-accent rounded-lg flex items-center justify-center text-foreground professional-text font-medium flex-shrink-0 text-sm">
                    4
                  </div>
                  <div>
                    <h3 className="text-base text-foreground heading-text mb-2">Monthly Payouts</h3>
                    <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                      Receive your commissions monthly via cryptocurrency or bank transfer. Minimum payout threshold: $100.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Who Should Apply */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7 }}
            className="mb-20"
          >
            <h2 className="text-2xl md:text-3xl text-foreground mb-8 heading-text">
              Ideal Affiliate Partners
            </h2>
            
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-accent/30 p-6 border border-border rounded-lg">
                <h3 className="text-lg text-foreground heading-text mb-3">Content Creators</h3>
                <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                  Cryptocurrency educators, YouTubers, bloggers, and influencers with engaged audiences interested in privacy-focused trading.
                </p>
              </div>

              <div className="bg-accent/30 p-6 border border-border rounded-lg">
                <h3 className="text-lg text-foreground heading-text mb-3">Community Leaders</h3>
                <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                  Telegram group admins, Discord moderators, and crypto community organizers with active trading communities.
                </p>
              </div>

              <div className="bg-accent/30 p-6 border border-border rounded-lg">
                <h3 className="text-lg text-foreground heading-text mb-3">Web Publishers</h3>
                <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                  Cryptocurrency news sites, comparison platforms, and review websites with established traffic.
                </p>
              </div>

              <div className="bg-accent/30 p-6 border border-border rounded-lg">
                <h3 className="text-lg text-foreground heading-text mb-3">Business Partners</h3>
                <p className="text-[15px] text-muted-foreground professional-text leading-relaxed">
                  Service providers, merchants, and businesses looking to offer cryptocurrency exchange services to their customers.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Why Partner with Us */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.8 }}
            className="mb-20"
          >
            <h2 className="text-2xl md:text-3xl text-foreground mb-8 heading-text">
              Why Partner with Cryptocoop
            </h2>
            
            <div className="bg-gradient-to-br from-primary/10 to-primary/5 p-10 border border-primary/20 rounded-lg">
              <div className="space-y-4 text-[15px] text-foreground/90 professional-text leading-relaxed">
                <div className="flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-primary mt-0.5 flex-shrink-0" strokeWidth={1.5} />
                  <p>
                    <span className="font-medium text-foreground">Proven Track Record:</span> $26M+ volume, 21,800+ trades, #1 ranked on LocalCoinSwap
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-primary mt-0.5 flex-shrink-0" strokeWidth={1.5} />
                  <p>
                    <span className="font-medium text-foreground">Privacy-Focused Platform:</span> Appeals to users seeking financial sovereignty and discretion
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-primary mt-0.5 flex-shrink-0" strokeWidth={1.5} />
                  <p>
                    <span className="font-medium text-foreground">Seamless Experience:</span> Telegram integration creates frictionless onboarding
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-primary mt-0.5 flex-shrink-0" strokeWidth={1.5} />
                  <p>
                    <span className="font-medium text-foreground">Global Reach:</span> 150+ countries, 50+ payment methods maximize conversion potential
                  </p>
                </div>
                <div className="flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-primary mt-0.5 flex-shrink-0" strokeWidth={1.5} />
                  <p>
                    <span className="font-medium text-foreground">Performance Analytics:</span> Comprehensive tracking and reporting tools
                  </p>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Marketing Materials */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.9 }}
            className="mb-20"
          >
            <h2 className="text-2xl md:text-3xl text-foreground mb-8 heading-text">
              Marketing Support
            </h2>
            
            <div className="bg-card p-8 border border-border rounded-lg">
              <p className="text-[15px] text-muted-foreground professional-text leading-relaxed mb-6">
                We provide comprehensive marketing materials to help you succeed:
              </p>
              
              <div className="grid md:grid-cols-2 gap-4">
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                  <div>
                    <p className="text-sm text-foreground professional-text font-medium mb-1">Branded Assets</p>
                    <p className="text-sm text-muted-foreground professional-text">Logos, banners, and graphics in multiple sizes</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                  <div>
                    <p className="text-sm text-foreground professional-text font-medium mb-1">Copy Templates</p>
                    <p className="text-sm text-muted-foreground professional-text">Pre-written promotional content and email templates</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                  <div>
                    <p className="text-sm text-foreground professional-text font-medium mb-1">Landing Pages</p>
                    <p className="text-sm text-muted-foreground professional-text">Optimized conversion pages for your traffic</p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-primary rounded-full mt-2 flex-shrink-0" />
                  <div>
                    <p className="text-sm text-foreground professional-text font-medium mb-1">Campaign Guidance</p>
                    <p className="text-sm text-muted-foreground professional-text">Best practices and optimization tips from our team</p>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Terms */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.0 }}
            className="mb-20"
          >
            <h2 className="text-2xl md:text-3xl text-foreground mb-8 heading-text">
              Program Terms
            </h2>
            
            <div className="bg-accent/30 p-8 border border-border rounded-lg">
              <div className="space-y-4 text-[15px] text-muted-foreground professional-text leading-relaxed">
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-foreground rounded-full mt-2 flex-shrink-0" />
                  <p><span className="text-foreground font-medium">Cookie Duration:</span> Lifetime attribution on all referrals</p>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-foreground rounded-full mt-2 flex-shrink-0" />
                  <p><span className="text-foreground font-medium">Payment Schedule:</span> Monthly payouts on the 1st of each month</p>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-foreground rounded-full mt-2 flex-shrink-0" />
                  <p><span className="text-foreground font-medium">Minimum Payout:</span> $100 USD equivalent</p>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-foreground rounded-full mt-2 flex-shrink-0" />
                  <p><span className="text-foreground font-medium">Payment Methods:</span> Cryptocurrency (USDT, BTC) or bank transfer</p>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-foreground rounded-full mt-2 flex-shrink-0" />
                  <p><span className="text-foreground font-medium">Reporting:</span> Real-time dashboard access with detailed metrics</p>
                </div>
                <div className="flex items-start gap-3">
                  <div className="w-1.5 h-1.5 bg-foreground rounded-full mt-2 flex-shrink-0" />
                  <p><span className="text-foreground font-medium">Support:</span> Dedicated affiliate manager for qualified partners</p>
                </div>
              </div>
            </div>
          </motion.div>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.1 }}
            className="text-center"
          >
            <div className="bg-gradient-to-br from-accent/20 to-accent/10 p-10 border border-accent/50 rounded-lg">
            <h2 className="text-2xl text-foreground heading-text mb-4">
              Become a Partner
            </h2>
            <p className="text-[15px] text-muted-foreground professional-text mb-8 max-w-2xl mx-auto leading-relaxed">
              Join our network of partners earning from trading volume. Commission terms are tailored to each partnership based on audience and expected performance.
            </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <a
                  href="mailto:hello@cryptocoop.info?subject=Affiliate Program Application"
                  className="inline-flex items-center gap-2 bg-foreground text-background px-6 py-3 rounded-md professional-text font-medium hover:opacity-90 transition-opacity elevated-shadow"
                >
                  Apply Now
                  <ArrowRight className="w-4 h-4" strokeWidth={1.5} />
                </a>
                <a
                  href="https://t.me/RealCryptoCoop"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 bg-white border border-border text-foreground px-6 py-3 rounded-md professional-text font-medium hover:bg-accent/30 transition-colors"
                >
                  Ask Questions
                  <ExternalLink className="w-4 h-4" strokeWidth={1.5} />
                </a>
              </div>
            </div>
          </motion.div>
        </motion.div>
      </section>
      <Footer />
    </main>
  );
}
